spring.application.name=oracle-db-mcp-toolkit-oauth2

server.port=9000
spring.security.oauth2.authorizationserver.issuer=http://localhost:9000

spring.security.user.name=user
spring.security.user.password=password

spring.security.oauth2.authorizationserver.client.mcp-client.registration.client-id=mcp-client
spring.security.oauth2.authorizationserver.client.mcp-client.registration.client-secret={noop}mcp-secret
spring.security.oauth2.authorizationserver.client.mcp-client.registration.client-name=MCP Client
spring.security.oauth2.authorizationserver.client.mcp-client.registration.client-authentication-methods=client_secret_basic
spring.security.oauth2.authorizationserver.client.mcp-client.registration.authorization-grant-types=client_credentials
spring.security.oauth2.authorizationserver.client.mcp-client.registration.scopes=mcp.access
